<a href="https://colab.research.google.com/github/PatrickHuynh837/MMAlytics/blob/main/model.ip_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Setup

In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import psycopg2
import sys
import os
from preprocessing import *

DB_URL = (
"postgresql+psycopg://neondb_owner:npg_Bo2SUY6ngypR@"
    "ep-orange-frost-afcl94sd-pooler.c-2.us-west-2.aws.neon.tech/"
    "neondb?sslmode=require"

)

engine = create_engine(
        DB_URL,
        pool_pre_ping=True,
        pool_recycle=3600
        )

In [2]:
#Loading Data
df = pd.read_sql(
    """
    SELECT *
    FROM ml.fight_dataset
    """,
    engine
)

df.head()

,fight_url,event_url,event_name,event_date,location_city,location_state,location_country,referee,weight_class,gender,...,fighter_2_takedown_att,fighter_2_takedown_succ,fighter_2_submission_att,fighter_2_reversals,fighter_2_ctrl_time,fighter_1_rank,fighter_2_rank,fighter_1_odds,fighter_2_odds,created_at
0,http://ufcstats.com/fight-details/c13dc0cccef2...,http://ufcstats.com/event-details/31e1ea6fe6b6...,UFC Fight Night: Fiziev vs. Torres,2026-06-27,Baku,Azerbaijan,None,Marc Goddard,Lightweight,M,...,0.0,0.0,0.0,0.0,0:06,11.0,15.0,NaN,NaN,2026-06-29 05:32:18.095360
1,http://ufcstats.com/fight-details/81cde317c156...,http://ufcstats.com/event-details/31e1ea6fe6b6...,UFC Fight Night: Fiziev vs. Torres,2026-06-27,Baku,Azerbaijan,None,Herb Dean,Flyweight,M,...,0.0,0.0,1.0,0.0,0:00,8.0,14.0,NaN,NaN,2026-06-29 05:32:18.095360
2,http://ufcstats.com/fight-details/809814f03ff3...,http://ufcstats.com/event-details/31e1ea6fe6b6...,UFC Fight Night: Fiziev vs. Torres,2026-06-27,Baku,Azerbaijan,None,Rich Mitchell,Lightweight,M,...,0.0,0.0,0.0,0.0,0:03,NaN,NaN,NaN,NaN,2026-06-29 05:32:18.095360
3,http://ufcstats.com/fight-details/012c307c9d44...,http://ufcstats.com/event-details/31e1ea6fe6b6...,UFC Fight Night: Fiziev vs. Torres,2026-06-27,Baku,Azerbaijan,None,Herb Dean,Middleweight,M,...,2.0,0.0,0.0,0.0,4:04,NaN,14.0,NaN,NaN,2026-06-29 05:32:18.095360
4,http://ufcstats.com/fight-details/6a35ff33b859...,http://ufcstats.com/event-details/31e1ea6fe6b6...,UFC Fight Night: Fiziev vs. Torres,2026-06-27,Baku,Azerbaijan,None,Rich Mitchell,Welterweight,M,...,0.0,0.0,0.0,0.0,0:03,NaN,NaN,NaN,NaN,2026-06-29 05:32:18.095360

# Scope

In [4]:

#Find missing data
missing = (
    df.isna()
      .sum()
      .sort_values(ascending=False)
      .to_frame('missing_count')
)

missing

                    missing_count
fighter_2_rank               7026
fighter_1_rank               6158
fighter_1_odds               2497
fighter_2_odds               2497
fighter_2_reach_cm            910
...                           ...
fighter_2_sapm                  0
fighter_2_td_def                0
fighter_2_td_acc                0
fighter_2_sub_avg               0
created_at                      0

[78 rows x 1 columns]

In [ ]:
list(df.columns)

['fight_url',
 'event_url',
 'event_name',
 'event_date',
 'location_city',
 'location_state',
 'location_country',
 'referee',
 'weight_class',
 'gender',
 'title_fight',
 'num_rounds',
 'fighter_1',
 'fighter_2',
 'fighter_1_url',
 'fighter_2_url',
 'winner',
 'result',
 'result_details',
 'finish_round',
 'finish_time',
 'fighter_1_height_cm',
 'fighter_1_weight_lbs',
 'fighter_1_reach_cm',
 'fighter_1_stance',
 'fighter_1_dob',
 'fighter_2_height_cm',
 'fighter_2_weight_lbs',
 'fighter_2_reach_cm',
 'fighter_2_stance',
 'fighter_2_dob',
 'fighter_1_wins',
 'fighter_1_losses',
 'fighter_1_draws',
 'fighter_1_slpm',
 'fighter_1_str_acc',
 'fighter_1_sapm',
 'fighter_1_str_def',
 'fighter_1_td_avg',
 'fighter_1_td_acc',
 'fighter_1_td_def',
 'fighter_1_sub_avg',
 'fighter_2_wins',
 'fighter_2_losses',
 'fighter_2_draws',
 'fighter_2_slpm',
 'fighter_2_str_acc',
 'fighter_2_sapm',
 'fighter_2_str_def',
 'fighter_2_td_avg',
 'fighter_2_td_acc',
 'fighter_2_td_def',
 'fighter_2_sub_avg',
 'fighter_1_knockdowns',
 'fighter_1_total_strikes_att',
 'fighter_1_total_strikes_succ',
 'fighter_1_sig_strikes_att',
 'fighter_1_sig_strikes_succ',
 'fighter_1_takedown_att',
 'fighter_1_takedown_succ',
 'fighter_1_submission_att',
 'fighter_1_reversals',
 'fighter_1_ctrl_time',
 'fighter_2_knockdowns',
 'fighter_2_total_strikes_att',
 'fighter_2_total_strikes_succ',
 'fighter_2_sig_strikes_att',
 'fighter_2_sig_strikes_succ',
 'fighter_2_takedown_att',
 'fighter_2_takedown_succ',
 'fighter_2_submission_att',
 'fighter_2_reversals',
 'fighter_2_ctrl_time',
 'fighter_1_rank',
 'fighter_2_rank',
 'fighter_1_odds',
 'fighter_2_odds',
 'created_at']

# Data Cleaning

## Exploration

### Reach

In [ ]:
missing_fighters = df.loc[
    df["fighter_1_reach_cm"].isna(),
    "fighter_1"
].unique()

fighters_in_both = [
    fighter for fighter in missing_fighters
    if ((df["fighter_1"] == fighter) | (df["fighter_2"] == fighter)).sum() > 1
]

fighters_in_both

['Din Thomas',
 'David Michaud',
 'Ben Wall',
 'Gan McGee',
 'Jutaro Nakao',
 'Geza Kalman',
 'Marcio Cruz',
 'Mark Hall',
 'Royce Gracie',
 'Remco Pardoel',
 'Patrick Smith',
 'Nick Penner',
 'Sam Adkins',
 'Horacio Gutierrez',
 'Matt Van Buren',
 'Tateki Matsuda',
 'Charlie Ward',
 'Luiz Dutra',
 'Nolan Ticman',
 'Wagner Silva',
 'Papy Abedi',
 'Kelly Faszholz',
 'Nate Loughran',
 'Steve Montgomery',
 'War Machine',
 'Tim Lajcik',
 'Don Frye',
 'Cal Worsham',
 'Keith Hackney',
 'Kwan Ho Kwak',
 'Alan Omer',
 'Wendell Oliveira Marques',
 'Ricardo Abreu',
 'Tor Troeng',
 'Marcus Bossett',
 'Juan Manuel Puig',
 'Ron Waterman',
 'Mike Lullo',
 'Paul Jones',
 'Mark Kerr',
 'Paul Varelans',
 'Carlos Newton',
 'Genki Sudo',
 'Joe Charles',
 'Jason DeLucia',
 'Mike van Arsdale',
 'Kevin Jackson',
 'Ivan Salaverry',
 'Semmy Schilt',
 'Anying Wang',
 'Laverne Clark',
 'Maurice Smith',
 'Brian Johnston',
 'Gary Goodridge',
 'Kevin Randleman',
 'David Abbott',
 'Kimo Leopoldo',
 'Anthony Macias',
 'Waylon Lowe',
 'Yui Chul Nam',
 'Roman Salazar',
 'Joseph Gigliotti',
 'Cesar Arzamendia',
 'Hernani Perpetuo',
 'Andreas Stahl',
 'Sai Wang',
 'Ian Loveland',
 'Jake Rosholt',
 'Mike Ciesnolevicz',
 'Matt Veach',
 'Dan Cramer',
 'Junie Browning',
 'Steve Bruno',
 'Troy Mandaloniz',
 'Roman Mitichyan',
 'Pete Spratt',
 'Anthony Torres',
 'Mike Nickels',
 'David Terrell',
 'Dan Christison',
 'Jason Von Flue',
 'Sam Hoger',
 'Branden Lee Hinkle',
 'Justin Eilers',
 'Renato Verissimo',
 'Wesley Correira',
 'Pedro Rizzo',
 'Keith Rockel',
 'Scott Morris',
 'Vernon White',
 'Falaniko Vitale',
 'Dave Strasser',
 'Phillip Miller',
 'Ricco Rodriguez',
 'Ian Freeman',
 'Mark Weir',
 'Benji Radach',
 'Tony Fryklund',
 'Murilo Bustamante',
 'Andrei Semenov',
 'Gil Castillo',
 'Eugene Jackson',
 'Dave Menne',
 'Pat Miletich',
 'Shonie Carter',
 'Fabiano Iha',
 'Bobby Hoffman',
 'Yuki Kondo',
 'Brad Gumm',
 'Amaury Bitetti',
 'Orlando Wiet',
 'Tedd Williams',
 'Lance Gibson',
 'Kenichi Yamamoto',
 'Joe Slick',
 'Katsuhisa Fujii',
 'Frank Shamrock',
 'Brad Kohler',
 'Tsuyoshi Kohsaka',
 'Andre Roberts',
 'Travis Fulton',
 'Bas Rutten',
 'Pete Williams',
 'Mikey Burnett',
 'Jerry Bohlander',
 'Chris Brennan',
 'Kazushi Sakuraba',
 'Tra Telligman',
 'Dave Beneteau',
 'Dwayne Cason',
 'Alex Hunter',
 'Dan Bobish',
 'Joe Moreira',
 'Guy Mezger',
 'Steven Graham',
 'Scott Ferrozzo',
 'Tai Bowden',
 'Steve Nelmark',
 'Roberto Traven',
 'Dan Severn',
 'Oleg Taktarov',
 'Marco Ruas',
 'Scott Bessac',
 'Joel Sutton',
 'Todd Medina',
 'Steve Jennum',
 'Nick Sanzo',
 'Johnny Rhodes',
 'Jack Nilson',
 'Harold Howard',
 'Jumabieke Tuerxun',
 'Chris Holdsworth',
 'Colin Fletcher',
 'Keith Wisniewski',
 'Joseph Sandoval',
 'Jonavin Webb',
 "Roldan Sangcha'an",
 'Alexis Dufresne',
 'Julie Kedzie',
 'Jesse Bongfeldt',
 'Pascal Krauss',
 'Anna Elmose',
 'Yasuhiro Urushitani',
 'Yusuke Kasuya',
 'Patrick Walsh',
 'Dan Stittgen',
 'Keith Berish',
 'Bubba Bush',
 'Larissa Pacheco',
 'Anthony Lapsley',
 'Thiago Perpetuo',
 'Ednaldo Oliveira',
 'Mike Stumpf',
 'Marcos Vinicius',
 'Buddy Roberts',
 'Jason Miller',
 'Alex Soto',
 'Jose Maria',
 'Pat Audinwood',
 'Steve Lopez',
 'Todd Brown',
 'Cody East',
 'Bruno Santos',
 'Richardson Moreira',
 'Pearl Gonzalez',
 'Niklas Backstrom',
 'Joao Zeferino',
 'Ian Entwistle',
 'Hayder Hassan',
 'Jessica Rakoczy',
 'Marcin Bandel',
 'Jorge de Oliveira',
 'Kalindra Faria',
 'John Lewis',
 'Emily Kagan',
 'Ramiro Hernandez',
 'Jake Lindsey',
 'Alberto Uda',
 'Anthony Christodoulou',
 'Chris Indich',
 'Estevan Payan',
 'Nah-Shon Burrell',
 'Rosi Sexton']

In [ ]:
missing_urls = pd.concat([
    df.loc[df["fighter_1_reach_cm"].isna(), "fighter_1_url"],
    df.loc[df["fighter_2_reach_cm"].isna(), "fighter_2_url"]
]).dropna().unique()

print(len(missing_urls))

666

### Weight

In [ ]:
df[df["fighter_1_weight_lbs"].isna()][
    ["fighter_1","fighter_1_url","weight_class"]
]

,fighter_1,fighter_1_url,weight_class
5696,Cesar Marscucci,http://ufcstats.com/fighter-details/e8efeb9cf3...,Lightweight
5934,Frank Hamaker,http://ufcstats.com/fighter-details/c3c23c9947...,Open Weight
6059,Jack Nilson,http://ufcstats.com/fighter-details/53e533db1b...,Lightweight

In [ ]:
df[df["fighter_2_weight_lbs"].isna()][
    ["fighter_2","fighter_2_url","weight_class"]
]

,fighter_2,fighter_2_url,weight_class
1300,Frank Caracci,http://ufcstats.com/fighter-details/44f9c777fe...,Lightweight
1320,Sam Fulton,http://ufcstats.com/fighter-details/1f5f756585...,Heavyweight
1334,Jack Nilson,http://ufcstats.com/fighter-details/53e533db1b...,Open Weight
1373,He-Man Gipson,http://ufcstats.com/fighter-details/3e03cec976...,Open Weight
2108,Felix Lee Mitchell,http://ufcstats.com/fighter-details/6cbb7661c3...,Open Weight
3378,Eric Martin,http://ufcstats.com/fighter-details/abbc4fc02e...,Heavyweight
3387,Dave Berry,http://ufcstats.com/fighter-details/b3bbe88fec...,Open Weight
3432,Jack McGlaughlin,http://ufcstats.com/fighter-details/237187ed9f...,Open Weight
5681,Sam Fulton,http://ufcstats.com/fighter-details/1f5f756585...,Open Weight
5696,Paulo Santos,http://ufcstats.com/fighter-details/7ca4c3f8aa...,Lightweight
5831,Francesco Maturi,http://ufcstats.com/fighter-details/d3b5ad3b15...,Open Weight
5877,Jackie Lee,http://ufcstats.com/fighter-details/4985113c09...,Lightweight
5879,Felix Lee Mitchell,http://ufcstats.com/fighter-details/6cbb7661c3...,Open Weight
5935,Ray Wizard,http://ufcstats.com/fighter-details/ea0ad15545...,Open Weight
6058,Adriano Santos,http://ufcstats.com/fighter-details/c6e6926a81...,Middleweight
6059,Saeed Hosseini,http://ufcstats.com/fighter-details/21f2974fd0...,Lightweight
6408,Felix Lee Mitchell,http://ufcstats.com/fighter-details/6cbb7661c3...,Open Weight
6512,John Dowdy,http://ufcstats.com/fighter-details/e780ccc79a...,Open Weight
7465,Noe Hernandez,http://ufcstats.com/fighter-details/df2cf66d8c...,Middleweight

## Preprocessing

In [3]:
df = preprocess_ranks(df)
df = preprocess_weight(df)

df["fighter_1_win"] = (df["winner"] == df["fighter_1"]).astype(int)

df = df.reset_index(drop=True)
df["fight_id"] = df.index

history = build_fighter_history(df)

df = add_fighter_cumulative_features(df, history)
df = add_striking_rolling_features(df, history)
df = add_grappling_rolling_features(df, history)

In [4]:
df["fighter_1_win"] = (df["winner"] == df["fighter_1"]).astype(int)

# Feature Engineering

## Creation

In [4]:
#Differentials



#Physical
df['height_diff'] = df['fighter_1_height_cm'] - df['fighter_2_height_cm']
df['reach_diff'] = df['fighter_1_reach_cm'] - df['fighter_2_reach_cm']
df['weight_diff'] = df['fighter_1_weight_lbs'] - df['fighter_2_weight_lbs']
df["age_diff"] = (
    (pd.to_datetime(df["event_date"]) - pd.to_datetime(df["fighter_1_dob"])).dt.days -
    (pd.to_datetime(df["event_date"]) - pd.to_datetime(df["fighter_2_dob"])).dt.days
) / 365.25


#Record
df['win_diff'] = (
    df['fighter_1_prior_wins']
    - df['fighter_2_prior_wins']
)

df['loss_diff'] = (
    df['fighter_1_prior_losses']
    - df['fighter_2_prior_losses']
)

df['draw_diff'] = (
    df['fighter_1_prior_draws']
    - df['fighter_2_prior_draws']
)



# Striking (rolling averages already merged)
df["slpm_roll_3_diff"] = (
    df["fighter_1_slpm_roll_3"]
    - df["fighter_2_slpm_roll_3"]
)

df["sapm_roll_3_diff"] = (
    df["fighter_1_sapm_roll_3"]
    - df["fighter_2_sapm_roll_3"]
)

df["str_acc_roll_3_diff"] = (
    df["fighter_1_str_acc_roll_3"]
    - df["fighter_2_str_acc_roll_3"]
)

df["str_def_roll_3_diff"] = (
    df["fighter_1_str_def_roll_3"]
    - df["fighter_2_str_def_roll_3"]
)

# #Grappling
df["td_avg_roll_3_diff"] = (
    df["fighter_1_td_avg_roll_3"]
    - df["fighter_2_td_avg_roll_3"]
)

df["td_acc_roll_3_diff"] = (
    df["fighter_1_td_acc_roll_3"]
    - df["fighter_2_td_acc_roll_3"]
)

df["td_def_roll_3_diff"] = (
    df["fighter_1_td_def_roll_3"]
    - df["fighter_2_td_def_roll_3"]
)

df["sub_avg_roll_3_diff"] = (
    df["fighter_1_sub_avg_roll_3"]
    - df["fighter_2_sub_avg_roll_3"]
)

df["ctrl_time_roll_3_diff"] = (
    df["fighter_1_ctrl_time_roll_3"]
    - df["fighter_2_ctrl_time_roll_3"]
)

df["td_success_rate_roll_3_diff"] = (
    df["fighter_1_td_success_rate_roll_3"]
    - df["fighter_2_td_success_rate_roll_3"]
)

#Perception
df["rank_diff"] = df["fighter_2_rank"] - df["fighter_1_rank"]
df['odds_diff'] = df['fighter_1_odds'] - df['fighter_2_odds']

## Selection

In [5]:
feature_cols = [
    # Physical
    "height_diff",
    "reach_diff",
    "weight_diff",
    "age_diff",

    # Record
    "win_diff",
    "loss_diff",
    "draw_diff",

    # Striking
    "slpm_roll_3_diff",
    "sapm_roll_3_diff",
    "str_acc_roll_3_diff",
    "str_def_roll_3_diff",

    # Grappling
    "td_avg_roll_3_diff",
    "td_acc_roll_3_diff",
    "td_def_roll_3_diff",
    "sub_avg_roll_3_diff",
    "ctrl_time_roll_3_diff",
    "td_success_rate_roll_3_diff",

    # Perception
    "rank_diff",
    "odds_diff"
]

df = df.sort_values("event_date")


X = df[feature_cols]

y = df["fighter_1_win"]

## Transformation

# Model Construction

### Logistic Regression

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix
)
from sklearn.metrics import classification_report
from sklearn.model_selection import RandomizedSearchCV, TimeSeriesSplit

In [7]:
pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(class_weight='balanced', max_iter=1000))
])


split_idx = int(len(df) * 0.8)

train_df = df.iloc[:split_idx]
test_df = df.iloc[split_idx:]

X_train = train_df[feature_cols]
y_train = train_df["fighter_1_win"]

X_test = test_df[feature_cols]
y_test = test_df["fighter_1_win"]

pipeline.fit(X_train, y_train)

preds = pipeline.predict(X_test)
probs = pipeline.predict_proba(X_test)[:, 1]

accuracy = accuracy_score(y_test, preds)

In [ ]:
y.value_counts()

fighter_1_win
1    5519
0    3239
Name: count, dtype: int64

In [8]:
print(f"Accuracy:  {accuracy_score(y_test, preds):.4f}")
print(f"Precision: {precision_score(y_test, preds):.4f}")
print(f"Recall:    {recall_score(y_test, preds):.4f}")
print(f"F1 Score:  {f1_score(y_test, preds):.4f}")
print(classification_report(y_test, preds))
print(f"ROC AUC:   {roc_auc_score(y_test, probs):.4f}")

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, preds))

Accuracy:  0.6592
Precision: 0.6946
Recall:    0.6795
F1 Score:  0.6869
              precision    recall  f1-score   support

           0       0.62      0.63      0.63       788
           1       0.69      0.68      0.69       964

    accuracy                           0.66      1752
   macro avg       0.66      0.66      0.66      1752
weighted avg       0.66      0.66      0.66      1752

ROC AUC:   0.7177

Confusion Matrix:
[[500 288]
 [309 655]]

### Boosted Trees

In [9]:
from sklearn.ensemble import RandomForestClassifier

# Random Forest
rf_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("model", RandomForestClassifier(random_state=42, class_weight= 'balanced'))
])

rf_pipeline.fit(X_train, y_train)

rf_preds = rf_pipeline.predict(X_test)
rf_probs = rf_pipeline.predict_proba(X_test)[:, 1]

In [10]:
print(f"Accuracy:  {accuracy_score(y_test, rf_preds):.4f}")
print(f"Precision: {precision_score(y_test, rf_preds):.4f}")
print(f"Recall:    {recall_score(y_test, rf_preds):.4f}")
print(f"F1 Score:  {f1_score(y_test, rf_preds):.4f}")
print(classification_report(y_test, rf_preds))
print(f"ROC AUC:   {roc_auc_score(y_test, rf_probs):.4f}")

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, rf_preds))

Accuracy:  0.6130
Precision: 0.6059
Recall:    0.8485
F1 Score:  0.7070
              precision    recall  f1-score   support

           0       0.64      0.32      0.43       788
           1       0.61      0.85      0.71       964

    accuracy                           0.61      1752
   macro avg       0.62      0.59      0.57      1752
weighted avg       0.62      0.61      0.58      1752

ROC AUC:   0.6765

Confusion Matrix:
[[256 532]
 [146 818]]

In [11]:
from xgboost import XGBClassifier

xgb_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("model", XGBClassifier(
        n_estimators=500,
    learning_rate=0.05,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.1,
    reg_lambda=1.0,
    min_child_weight=5,
    gamma=0.1,
    random_state=42,
    eval_metric="logloss",
    class_weight='balanced'

    ))
])

xgb_pipeline.fit(X_train, y_train)

xgb_preds = xgb_pipeline.predict(X_test)
xgb_probs = xgb_pipeline.predict_proba(X_test)[:, 1]

/home/patrickhuynh837/miniforge3/envs/MMAlytics/lib/python3.12/site-packages/xgboost/training.py:200: UserWarning: [14:16:46] WARNING: /__w/xgboost/xgboost/src/learner.cc:793:
Parameters: { "class_weight" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

In [12]:
print(f"Accuracy:  {accuracy_score(y_test, xgb_preds):.4f}")
print(f"Precision: {precision_score(y_test, xgb_preds):.4f}")
print(f"Recall:    {recall_score(y_test, xgb_preds):.4f}")
print(f"F1 Score:  {f1_score(y_test, xgb_preds):.4f}")
print(classification_report(y_test, xgb_preds))
print(f"ROC AUC:   {roc_auc_score(y_test, xgb_probs):.4f}")

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, xgb_preds))

Accuracy:  0.6267
Precision: 0.6234
Recall:    0.8122
F1 Score:  0.7054
              precision    recall  f1-score   support

           0       0.64      0.40      0.49       788
           1       0.62      0.81      0.71       964

    accuracy                           0.63      1752
   macro avg       0.63      0.61      0.60      1752
weighted avg       0.63      0.63      0.61      1752

ROC AUC:   0.6728

Confusion Matrix:
[[315 473]
 [181 783]]

d

In [ ]:
list(df.columns)

['fight_id',
 'fight_url',
 'event_url',
 'event_name',
 'event_date',
 'location_city',
 'location_state',
 'location_country',
 'referee',
 'weight_class',
 'gender',
 'title_fight',
 'num_rounds',
 'fighter_1',
 'fighter_2',
 'fighter_1_url',
 'fighter_2_url',
 'winner',
 'result',
 'result_details',
 'finish_round',
 'finish_time',
 'fighter_1_height_cm',
 'fighter_1_weight_lbs',
 'fighter_1_reach_cm',
 'fighter_1_stance',
 'fighter_1_dob',
 'fighter_2_height_cm',
 'fighter_2_weight_lbs',
 'fighter_2_reach_cm',
 'fighter_2_stance',
 'fighter_2_dob',
 'fighter_1_wins',
 'fighter_1_losses',
 'fighter_1_draws',
 'fighter_1_slpm',
 'fighter_1_str_acc',
 'fighter_1_sapm',
 'fighter_1_str_def',
 'fighter_1_td_avg',
 'fighter_1_td_acc',
 'fighter_1_td_def',
 'fighter_1_sub_avg',
 'fighter_2_wins',
 'fighter_2_losses',
 'fighter_2_draws',
 'fighter_2_slpm',
 'fighter_2_str_acc',
 'fighter_2_sapm',
 'fighter_2_str_def',
 'fighter_2_td_avg',
 'fighter_2_td_acc',
 'fighter_2_td_def',
 'fighter_2_sub_avg',
 'fighter_1_knockdowns',
 'fighter_1_total_strikes_att',
 'fighter_1_total_strikes_succ',
 'fighter_1_sig_strikes_att',
 'fighter_1_sig_strikes_succ',
 'fighter_1_takedown_att',
 'fighter_1_takedown_succ',
 'fighter_1_submission_att',
 'fighter_1_reversals',
 'fighter_1_ctrl_time',
 'fighter_2_knockdowns',
 'fighter_2_total_strikes_att',
 'fighter_2_total_strikes_succ',
 'fighter_2_sig_strikes_att',
 'fighter_2_sig_strikes_succ',
 'fighter_2_takedown_att',
 'fighter_2_takedown_succ',
 'fighter_2_submission_att',
 'fighter_2_reversals',
 'fighter_2_ctrl_time',
 'fighter_1_rank',
 'fighter_2_rank',
 'fighter_1_odds',
 'fighter_2_odds',
 'created_at',
 'fighter_1_is_ranked',
 'fighter_2_is_ranked',
 'fighter_1_win',
 'fighter_1_prior_wins',
 'fighter_1_prior_losses',
 'fighter_1_prior_draws',
 'fighter_2_prior_wins',
 'fighter_2_prior_losses',
 'fighter_2_prior_draws',
 'fighter_1_slpm_roll_3',
 'fighter_1_sapm_roll_3',
 'fighter_1_str_acc_roll_3',
 'fighter_1_str_def_roll_3',
 'fighter_2_slpm_roll_3',
 'fighter_2_sapm_roll_3',
 'fighter_2_str_acc_roll_3',
 'fighter_2_str_def_roll_3',
 'height_diff',
 'reach_diff',
 'weight_diff',
 'age_diff',
 'win_diff',
 'loss_diff',
 'draw_diff',
 'slpm_roll_3_diff',
 'sapm_roll_3_diff',
 'str_acc_roll_3_diff',
 'str_def_roll_3_diff',
 'td_avg_diff',
 'td_acc_diff',
 'td_def_diff',
 'sub_avg_diff',
 'rank_diff',
 'odds_diff']